### ISSUE TITLE
Inboxy loads with bundles

### ISSUE THREAD

**Issue by tapir-whorf** [teresa-ou/inboxy#102]
With Inboxy installed, Gmail loads with bundles displaying perfectly — then, within a second or two, the bundling vanishes and all emails contained under that bundle reappear in the 'main' inbox.

(Also, please consider writing up some documentation; this extension offers such valuable functionality, yet despite how simple its function and settings are, behavior isn't consistent enough to know whether it's working correctly! It'd be especially helpful to have a few troubleshooting tips for folks who don't have the skillset to review known issues on Github.)

**Comment by samuelalexmclean** [comment]
I've also lost bundle functionality over the last ~week.

```
inboxy-debug: Handle content loaded event
content.js:49 inboxy-debug: Url: https://mail.google.com/mail/u/0/#inbox, page supports bundling: true
content.js:176 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at tryBundling (content.js:176:1)
    at HTMLDocument.handleContentLoaded (content.js:146:1)
invalid/:1 Failed to load resource: net::ERR_FAILED
```

My line numbers are OBO vs what I see in the repo - [here](https://i.imgur.com/rn1zg0h.png) is the source view.

I've noticed this doesn't repro across all of my accounts + machines, which makes me think I'm in a % rollout for some subtle new variation on the UI.

Theresa, can you give me some tips on where I should be looking in the source to find the new element name? I don't want to paste my entire DOM here but it's a little bit tricky to tell what's meant to be where.

**Comment by leggett** [comment]
In case this still hasn't been fixed, you can try out bundling in [Simplify Gmail's v3 beta](https://beta.simpl.fyi) (Chrome only at this moment). I fully support keyboard shortcuts (J/K or arrow keys) and do a lot of things to prevent messages or bundles from jumping around unexpectedly when you archive things. I've also been [posting videos](https://www.youtube.com/playlist?list=PLOFrFbZRw8kKFFaQTQSLR3fEHW7mrLmMu) during development.

**Comment by samuelalexmclean** [comment]
Thanks Michael - unfortunately I run this in a corporate context and we need to fork + code review the extension (which only really works for FOSS). Will explore Simplify for my personal account though!

**Comment by leggett** [comment]
Sounds good. I tried FOSS for the first ~2 years but (a) it turned out to be way more work than I expected to maintain and (b) no one showed up to help. ¯\_(ツ)_/¯ 

If you happen to be at Google (the only place I've hit this so far), I work with some Googlers to maintain a version internally. I think you can get it at go/simplify-gmail

**Comment by tmenier** [comment]
Inboxy suddenly stopped working for me too, and it looks like that project hasn't been active in quite some time. Bummer, I really liked it. Here's another alternative that's free and works great for me so far (no affiliation to me):

https://chrome.google.com/webstore/detail/inbox-reborn-theme-for-gm/bkphmihkdbdgedlaflnkhnmnmibffomf

**Comment by benoror** [comment]
Hi! Bundles flashing then vanishing is the bug class we have been chasing hardest. **Inbundly** has soft-retry startup, late-row rebundle, and options-race fixes through v4.2.0.

Please try the latest build with other Gmail extensions disabled once. If it still disappears after 1-2 seconds, open a bug (browser, Workspace or not, other extensions). Happy to dig in.

Chrome: https://chromewebstore.google.com/detail/inbundly/pbfjicjmcpogjlbpljebhhgkgfhbdcga
Firefox: https://addons.mozilla.org/firefox/addon/inbundly/
Issues: https://github.com/benoror/inbundly/issues/new
